week19_complete
Monday-9AM/Legally-Sourced-Goods pull request #11
Opened 2021-02-16 12:14 UTC by fairywizard15

Completed week 19 lab sheet
New test methods

2021-02-16 12:47 UTC, Dylan773 commented on AdminSystem/Web.config
Framework change?

2021-02-16 13:23 UTC, Shinkson47 commented on ClassLibrary/clsStock.cs
> +        private int aProductId;
Fairly sure these privates were supposed to be prefaced with `p` not `a`

2021-02-16 13:24 UTC, Shinkson47 commented on ClassLibrary/clsStock.cs
> +            clsDataConnection DB = new clsDataConnection();
We shouldn't need to create this everytime, we can make this static.

2021-02-16 13:25 UTC, Shinkson47 commented on TestingStaff/UnitTest1.cs
> -﻿using Microsoft.VisualStudio.TestTools.UnitTesting;
Is this file needed? it's empty, and doesn't even include the testing libraries

2021-02-16 13:26 UTC, Shinkson47 commented on TestingStaff/tstStock.cs
> +            if(product.ProductName != "Product Name")
These test shouldn't use custom booleans, instead the test should be `Assert.IsTrue(product.ProductName != "Product Name")`

2021-02-16 13:29 UTC, Shinkson47 requested changes
Mostly looks good, just a could things to cover
- I'll add a static database reference
- tests need to use `Assert` for tests, instead of using if statements.
- There's a blank, unused test file that should be removed.

2021-02-16 13:40 UTC, Shinkson47 commented
Hold up, @fairywizard15 , the tests are done with bad practice but is that the way the lab sheets say to do them?

if so, fuck it. It's not good, but if they ask for it, they get it.

2021-02-16 13:51 UTC, Shinkson47 approved these changes
Close enough

2021-02-18 12:10 UTC, Dylan773 approved these changes
Good shit

2021-02-18 20:33 UTC, merged